### ISSUE TITLE
Dumping keychain error

### ISSUE THREAD

**Issue by nmonkee** [dmayer/idb#16]
When connected to a Jailbroken iOS 7 iDevice, after starting an app, if the option to dump keychain is chosen, the following error is received:

<pre>
<code>
[INFO] 2014-01-27 15:04:54 :: gidb ::  Dumping keychain...
[INFO] 2014-01-27 15:04:54 :: gidb ::  Downloading dumped keychain...
Error downloading file.
[INFO] 2014-01-27 15:04:54 :: gidb ::  Parsing keychain plist file..
/Users/nmonkee/tools/ios/idb/gui/key_chain_widget.rb:64:in `populate_table': undefined method `each' for nil:NilClass (NoMethodError)
    from /Users/nmonkee/tools/ios/idb/gui/key_chain_widget.rb:48:in `block in initialize'
    from /Library/Ruby/Gems/2.0.0/gems/qtbindings-4.8.3.0/lib/Qt/qtruby4.rb:2427:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/qtbindings-4.8.3.0/lib/Qt/qtruby4.rb:2427:in `invoke'
    from /Library/Ruby/Gems/2.0.0/gems/qtbindings-4.8.3.0/lib/Qt/qtruby4.rb:469:in `qt_metacall'
    from /Library/Ruby/Gems/2.0.0/gems/qtbindings-4.8.3.0/lib/Qt/qtruby4.rb:469:in `method_missing'
    from /Library/Ruby/Gems/2.0.0/gems/qtbindings-4.8.3.0/lib/Qt/qtruby4.rb:469:in `exec'
    from gidb.rb:244:in `<main>'
</code>
</pre>

**Comment by shanks114** [comment]
Hey dmayer Am facing some kind of issue while Downloading Info.plist can you please help me out here

IPHONE details as follows 
-IOS 10.0.2
-model 5S 

[DEBUG] 2017-06-18 05:06:52 :: idb ::  Executing blocking SSH command: /bin/su mobile -c /usr/bin/uicache
[*] Retrieving list of applications...
[DEBUG] 2017-06-18 05:07:22 :: idb ::  App Dir: /private/var/containers/Bundle/Application/127FA06B-3A8C-4811-A853-B3FB625ADC1C
[DEBUG] 2017-06-18 05:07:22 :: idb ::  Executing blocking SSH command: ls /private/var/containers/Bundle/Application/127FA06B-3A8C-4811-A853-B3FB625ADC1C/*app/Info.plist
[INFO] 2017-06-18 05:07:22 :: idb ::  Info.plist found at /private/var/containers/Bundle/Application/127FA06B-3A8C-4811-A853-B3FB625ADC1C/ServerAuditor.app/Info.plist
[INFO] 2017-06-18 05:07:22 :: idb ::  Parsing plist file..
[ERROR] 2017-06-18 05:07:22 :: idb ::  Error downloading file.
/usr/local/rvm/gems/ruby-2.1.10/gems/plist4r-1.2.2/lib/plist4r/plist.rb:294:in `open': No filename specified (RuntimeError)
	from /usr/local/rvm/gems/ruby-2.1.10/gems/plist4r-1.2.2/lib/plist4r.rb:34:in `open'
	from /root/git/idb/lib/lib/ios8_last_launch_services_map_wrapper.rb:7:in `initialize'
	from /root/git/idb/lib/lib/app.rb:29:in `new'
	from /root/git/idb/lib/lib/app.rb:29:in `initialize'
	from /root/git/idb/lib/gui/app_list_dialog.rb:74:in `new'
	from /root/git/idb/lib/gui/app_list_dialog.rb:74:in `block in refresh_app_list'
	from /root/git/idb/lib/gui/app_list_dialog.rb:73:in `each'
	from /root/git/idb/lib/gui/app_list_dialog.rb:73:in `refresh_app_list'
	from /root/git/idb/lib/gui/app_list_dialog.rb:31:in `initialize'
	from /root/git/idb/lib/gui/global_app_details_group_box.rb:43:in `new'
	from /root/git/idb/lib/gui/global_app_details_group_box.rb:43:in `block in initialize'
	from /usr/local/rvm/gems/ruby-2.1.10/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `call'
	from /usr/local/rvm/gems/ruby-2.1.10/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /usr/local/rvm/gems/ruby-2.1.10/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	from /usr/local/rvm/gems/ruby-2.1.10/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `method_missing'
	from /usr/local/rvm/gems/ruby-2.1.10/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `exec'
	from /root/git/idb/lib/idb.rb:278:in `run'
	from /root/git/idb/bin/idb:4:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.10/bin/idb:23:in `load'
	from /usr/local/rvm/gems/ruby-2.1.10/bin/idb:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `<main>'
