### ISSUE TITLE
idb Crashes With No Applications

### ISSUE THREAD

**Issue by aschmitz** [dmayer/idb#55]
When telling idb to select an application using an iPad with no extra applications on it, idb crashes. (That is, just the built-in apps, Cydia, and Pangu.) Installing an application allows idb to work properly.

This is iOS 8.1 on a MD517LL/A.

**Comment by jakev** [comment]
@dmayer @aschmitz this pull request should fix the issue: https://github.com/dmayer/idb/pull/56

**Comment by dmayer** [comment]
Closed via @jakev pull request and fb9e60efa42d39aa7a27349ea79c7d6b664cc488
