### ISSUE TITLE
keychaineditor crashes

### ISSUE THREAD

**Issue by 0x4d4e** [dmayer/idb#63]
The included keychaineditor binary crashed on my device, found out it is a known and fixed bug:
https://github.com/NitinJami/keychaineditor/issues/1

Replacing the included binary on the device with the following fixed the issue for me:
https://github.com/NitinJami/keychaineditor/blob/master/keychaineditor

**Comment by dmayer** [comment]
Hi,

Thanks for reporting this. I will update the package shortly to include the new keychain editor.
