### ISSUE TITLE
Log feature does not work

### ISSUE THREAD

**Issue by mfpp** [dmayer/idb#64]
Log feature does not work. Tested on iOS 9.0.2.

idb presents the following error message:

```
#<Thread:0x007fb2e90281d8>
No device found. Plug in a device or pass UDID with -u to wait for device to be available.
[*] Terminating thread
```

**Comment by dmayer** [comment]
Should be working with iOS. Try unlocking the device you may need to tap the "Trust this Computer" dialog the first time you connect the device.

**Comment by mfpp** [comment]
After a gem update the Log feature worked again...

Maybe I was using an old version of idb.
