### ISSUE TITLE
Does the device need to be jailbroken?

### ISSUE THREAD

**Issue by javixeneize** [dmayer/idb#66]
Hi

I am unable to use this framework as it needs to connect via ssh. As far as i know, you need to jailbreak the device to do it, isnt it?

Does this tool work by loading the .ipa directly from the computer, or connecting to a non-jailbroken device?

**Comment by jjarmoc** [comment]
The majority of features work by connecting via SSH, so you'll need a jailbroken device for those.  A few things might work without a jailbroken device, but not much.

> Note that you still need to have an SSH server running on the device (get it using Cydia) even if you are connecting via USB.
http://www.idbtool.com/documentation/setup.html

You can also run it against XCode's iOS simulator, but again functionality may be somewhat limited.
