### ISSUE TITLE
Crashes when trying to get applications

### ISSUE THREAD

**Issue by kunal-relan** [dmayer/idb#68]
Hey , the application crashes when i click on the button to fetch the list of applciations sending you the log snippet maybe could be of some help 

`[INFO] 2016-06-26 01:00:13 :: idb ::  Parsing plist file..
[ERROR] 2016-06-26 01:00:13 :: idb ::  Info.plist not found.
[ERROR] 2016-06-26 01:00:13 :: idb ::  Info.plist not found.
[ERROR] 2016-06-26 01:00:13 :: idb ::  Error getting plist file .
[DEBUG] 2016-06-26 01:00:13 :: idb ::  Exception Details: undefined method`sub' for nil:NilClass.
[DEBUG] 2016-06-26 01:00:13 :: idb ::  Backtrace: /usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/lib/app.rb:255:in `cache_file'
/usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/lib/app.rb:271:in`parse_info_plist'
/usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/lib/app.rb:17:in `initialize'
/usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/gui/app_list_dialog.rb:76:in`new'
/usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/gui/app_list_dialog.rb:76:in `block in refresh_app_list'
/usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/gui/app_list_dialog.rb:75:in`each'
/usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/gui/app_list_dialog.rb:75:in `refresh_app_list'
/usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/gui/app_list_dialog.rb:33:in`initialize'
/usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/gui/global_app_details_group_box.rb:43:in `new'
/usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/gui/global_app_details_group_box.rb:43:in`block in initialize'
/usr/local/lib/ruby/gems/2.3.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `invoke'
/usr/local/lib/ruby/gems/2.3.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in`qt_metacall'
/usr/local/lib/ruby/gems/2.3.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `method_missing'
/usr/local/lib/ruby/gems/2.3.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in`exec'
/usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/idb.rb:285:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/bin/idb:4:in`<top (required)>'
/usr/local/bin/idb:23:in `load'
/usr/local/bin/idb:23:in`<main>'.
/usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/lib/app.rb:24:in `initialize': undefined method`bundle_identifier' for nil:NilClass (NoMethodError)
    from /usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/gui/app_list_dialog.rb:76:in `new'
    from /usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/gui/app_list_dialog.rb:76:in`block in refresh_app_list'
    from /usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/gui/app_list_dialog.rb:75:in `each'
    from /usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/gui/app_list_dialog.rb:75:in`refresh_app_list'
    from /usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/gui/app_list_dialog.rb:33:in `initialize'
    from /usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/gui/global_app_details_group_box.rb:43:in`new'
    from /usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/gui/global_app_details_group_box.rb:43:in `block in initialize'
    from /usr/local/lib/ruby/gems/2.3.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in`invoke'
    from /usr/local/lib/ruby/gems/2.3.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `qt_metacall'
    from /usr/local/lib/ruby/gems/2.3.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in`method_missing'
    from /usr/local/lib/ruby/gems/2.3.0/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `exec'
    from /usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/lib/idb.rb:285:in`run'
    from /usr/local/lib/ruby/gems/2.3.0/gems/idb-2.8.5/bin/idb:4:in `<top (required)>'
    from /usr/local/bin/idb:23:in`load'
    from /usr/local/bin/idb:23:in `<main>'
recv failed: Resource temporarily unavailable
`

**Comment by tomekr** [comment]
Hi Kunal,

Not sure if you ended up resolving this issue but if not, would you have some more information on the iOS version you were running on?

According to the exception output you pasted, in the line "Error getting plist file .", it looks like there was an issue either getting the devices application directory or finding a valid plist file for a given app. As can be seen here, https://github.com/dmayer/idb/blob/master/lib/lib/app.rb#L273, there should be some file path being printed there and there isn't. 

Otherwise, does the `/private/var/mobile/Containers/Bundle/Application` directory exist on your device? If so, are there directories within that folder?

**Comment by dmayer** [comment]
closing this due to lack of feedback.
