### ISSUE TITLE
"Undefined method `gsub' for nil:NilClass (NoMethodError)" when using fuzzer

### ISSUE THREAD

**Issue by jakev** [dmayer/idb#69]
The "open_url" function (devices.rb) does not check if the "url" parameter is nil before attempting to call "gsub", which crashes `idb`. Should be a straightforward change and I can submit a PR tomorrow.

**Comment by jakev** [comment]
PR: https://github.com/dmayer/idb/pull/70

**Comment by jakev** [comment]
@dmayer not sure you saw this, but any reason not to merge?

**Comment by dmayer** [comment]
Hey, I finally merged this. Thanks a lot for the PR. I got really busy and idb got put on the back burner. Will be more responsive going forward :)
