### ISSUE TITLE
Feature Request: Support iOS 9.3.3

### ISSUE THREAD

**Issue by mickayz** [dmayer/idb#71]
Currently displays the following message in terminal with the most recent build: 

[ERROR] 2016-08-09 13:54:38 :: idb ::  Unsupported iOS Version.

Device is iPad Mini 4 running 9.3.3 jailbroken with Pangu.

Thanks! Love this tool!

**Comment by mickayz** [comment]
Note: dumpdecrypted fails on iOS 9.3.3 due to this issue

https://github.com/stefanesser/dumpdecrypted/issues/19

**Comment by fp9717** [comment]
[ERROR] 2016-09-17 23:12:43 :: idb ::  Unsupported iOS Version.

Any new for support in 9.3.3 ?

**Comment by dmayer** [comment]
Closing per #75
