### ISSUE TITLE
Selecting Preference Dialogue causes to idb crash??

### ISSUE THREAD

**Issue by aboutsajjad** [dmayer/idb#83]
After switching to another app and selecting Preference dialogue causes to idb crash Any Help??
ruby-2.1.10
macOS Sierra 
Tank you.

**Comment by Gaelstrom** [comment]
I too am experiencing the same issue where idb crashes on preferences dialog.  

Using RVM to install ruby 2.1 as directed and other prerequisites.  Only difference is I am running OSX El Capitan instead of Sierra.

Is there a previous idb version we can access to get it working?

**Comment by dmayer** [comment]
I will take a look soon. As for previous versions you should be able to install it via

`gem install idb -v [version_number]`

**Comment by Gaelstrom** [comment]
Apologize for this, but where can I see a list of previous versions...

**Comment by dmayer** [comment]
Thanks for the update. Here is a list of releases:

https://github.com/dmayer/idb/releases

**Comment by Gaelstrom** [comment]
Update - idb version 2.8.5 allowed preference dialogue interaction without crashing.

**Comment by forced-request** [comment]
I had the same issues on Sierra + iOS 9.3 with IDB 2.9.1. 

@Gaelnomaly 2.8.5 did not work for me. It threw an unsupported iOS version exception.

Downgrading to IDB 2.9.0 did the trick for me:

```
gem uninstall idb
gem install idb -v 2.9.0
```

**Comment by ghost** [comment]
-

**Comment by TimXcode** [comment]
I was having same problem. Downgrading to 2.8.5 worked for me. On Sierra 10.12.5

**Comment by dmayer** [comment]
This is also fixed in the latest version 2.9.2 (commit c87dc47770eb661f69831132c314b6ee2ff8326c)

`gem update idb` should get it
