### ISSUE TITLE
Clicking on preferences crashes idb [method_missing': undefined method `sqlite_editor']

### ISSUE THREAD

**Issue by dimpol** [dmayer/idb#86]
OSX Sierra:

Clicking on preferences crashes idb --> [method_missing': undefined method `sqlite_editor']
/Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/idb-2.9.1/lib/lib/settings.rb:56:in `rescue in method_missing': undefined method `sqlite_editor' for #<Idb::Settings:0x007fa5b2b9e740> (NoMethodError)

	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/idb-2.9.1/lib/lib/settings.rb:53:in `method_missing'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/idb-2.9.1/lib/gui/settings_tab_widget.rb:125:in `setup_external_apps'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/idb-2.9.1/lib/gui/settings_tab_widget.rb:15:in `initialize'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/idb-2.9.1/lib/gui/settings_dialog.rb:14:in `new'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/idb-2.9.1/lib/gui/settings_dialog.rb:14:in `initialize'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/idb-2.9.1/lib/idb.rb:150:in `new'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/idb-2.9.1/lib/idb.rb:150:in `block in menu'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `call'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `method_missing'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/qtbindings-4.8.6.3/lib/Qt/qtruby4.rb:479:in `exec'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/idb-2.9.1/lib/idb.rb:278:in `run'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/idb-2.9.1/bin/idb:4:in `<top (required)>'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/bin/idb:22:in `load'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/bin/idb:22:in `<main>'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `eval'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `<main>'

**Comment by zsolt-halo** [comment]
Answered here :)
https://github.com/dmayer/idb/issues/83
Just paste the appropriate settings template into ~/.idb/settings.yml

**Comment by dimpol** [comment]
2.9.0 did the trick. Closing it. Thanks a lot

**Comment by dmayer** [comment]
This is also fixed in the latest version 2.9.2 (commit c87dc47770eb661f69831132c314b6ee2ff8326c)
