### ISSUE TITLE
SSH Issue during connection

### ISSUE THREAD

**Issue by dimpol** [dmayer/idb#87]
OSX Sierra:

[INFO] 2017-02-18 11:32:16 :: port_forward ::  - Forwarding remote:4711 -> localhost:4711
/Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/net-ssh-4.0.0/lib/net/ssh/service/forward.rb:179:in `block in remote': remote forwarding request failed (Net::SSH::Exception)
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/net-ssh-4.0.0/lib/net/ssh/connection/session.rb:596:in `call'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/net-ssh-4.0.0/lib/net/ssh/connection/session.rb:596:in `request_failure'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/net-ssh-4.0.0/lib/net/ssh/connection/session.rb:540:in `dispatch_incoming_packets'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/net-ssh-4.0.0/lib/net/ssh/connection/session.rb:237:in `ev_preprocess'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/net-ssh-4.0.0/lib/net/ssh/connection/event_loop.rb:99:in `each'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/net-ssh-4.0.0/lib/net/ssh/connection/event_loop.rb:99:in `ev_preprocess'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/net-ssh-4.0.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/net-ssh-4.0.0/lib/net/ssh/connection/session.rb:216:in `process'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/net-ssh-4.0.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/net-ssh-4.0.0/lib/net/ssh/connection/session.rb:178:in `loop'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/net-ssh-4.0.0/lib/net/ssh/connection/session.rb:178:in `loop'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/idb-2.9.1/lib/lib/ssh_port_forwarder.rb:29:in `start'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/idb-2.9.1/lib/helper/ssh_port_forwarder.rb:58:in `run'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/idb-2.9.1/lib/helper/ssh_port_forwarder.rb:63:in `<module:Idb>'
	from /Users/x0rc1st/.rvm/gems/ruby-2.1.10/gems/idb-2.9.1/lib/helper/ssh_port_forwarder.rb:7:in `<main>'
recv failed: Resource temporarily unavailable

**Comment by brajbong** [comment]
what was the issue there? @dimpol
