### ISSUE TITLE
Crash when open file->setting menu

### ISSUE THREAD

**Issue by josebeo2016** [dmayer/idb#89]
As my subtitle, I can't open file->setting menu, the idb window is crash immediately. May I open connection to iOS 7.1.2 jailbroken?

**Comment by TimXcode** [comment]
Having the same problem :-/

**Comment by dmayer** [comment]
This should be fixed in c87dc47770eb661f69831132c314b6ee2ff8326c  
When no settings file existed, idb would not add the sqlite_editor option, resulting in a crash when reading it. 

Try a `gem update idb` and please let me know if the issue still exists.
