### ISSUE TITLE
Failed to run idb

### ISSUE THREAD

**Issue by manmanking** [dmayer/idb#93]
kade:~ manman$ idb
/Users/manman/.rvm/gems/ruby-2.4.1/gems/plist4r-1.2.2/lib/plist4r/mixin/data_methods.rb:13: warning: constant ::Fixnum is deprecated
/Users/manman/.rvm/gems/ruby-2.4.1/gems/plist4r-1.2.2/lib/plist4r/mixin/data_methods.rb:16: warning: constant ::Fixnum is deprecated
/Users/manman/.rvm/gems/ruby-2.4.1/gems/plist4r-1.2.2/lib/plist4r/mixin/data_methods.rb:20: warning: constant ::Fixnum is deprecated
/Users/manman/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pry (LoadError)
	from /Users/manman/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/manman/.rvm/gems/ruby-2.4.1/gems/idb-2.10.0/lib/lib/ios10_application_state_db_wrapper.rb:3:in `<top (required)>'
	from /Users/manman/.rvm/gems/ruby-2.4.1/gems/idb-2.10.0/lib/lib/app.rb:5:in `require_relative'
	from /Users/manman/.rvm/gems/ruby-2.4.1/gems/idb-2.10.0/lib/lib/app.rb:5:in `<top (required)>'
	from /Users/manman/.rvm/gems/ruby-2.4.1/gems/idb-2.10.0/lib/gui/app_details_group_box.rb:1:in `require_relative'
	from /Users/manman/.rvm/gems/ruby-2.4.1/gems/idb-2.10.0/lib/gui/app_details_group_box.rb:1:in `<top (required)>'
	from /Users/manman/.rvm/gems/ruby-2.4.1/gems/idb-2.10.0/lib/idb.rb:9:in `require_relative'
	from /Users/manman/.rvm/gems/ruby-2.4.1/gems/idb-2.10.0/lib/idb.rb:9:in `<top (required)>'
	from /Users/manman/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/manman/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/manman/.rvm/gems/ruby-2.4.1/gems/idb-2.10.0/bin/idb:2:in `<top (required)>'
	from /Users/manman/.rvm/gems/ruby-2.4.1/bin/idb:23:in `load'
	from /Users/manman/.rvm/gems/ruby-2.4.1/bin/idb:23:in `<main>'
	from /Users/manman/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/manman/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by stephengallo** [comment]
having the same exact issue when following instructions from http://www.idbtool.com/installation/

macOS 10.12.6 
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

**Comment by manmanking** [comment]
macOS 10.12.5
is the problem fixed,and how ?

**Comment by sh4hin** [comment]
Try to install it from the source code not through gem install idb

**Comment by stephengallo** [comment]
following the Development instructions from http://www.idbtool.com/installation/ and running from source worked for me.

**Comment by manmanking** [comment]
the problem is fixed!
command 
gem install bundler

**Comment by dmayer** [comment]
Hi, there was a leftover dependency in one of the files that was not installed when the gem was. I removed the dependency in 2.10.1 092929aa51b941e003f7e4d162b550171da8d66a
